[package]
name = "flamenco687/puzzle"

description = """
ECS library for Roblox. \
Homepage: https://flamenco687.github.io/Puzzle/
"""

version = "0.2.0"
license = "MIT"
authors = ["flamenco687"]

exclude = ["**"]
include = ["lib", "lib/*.lua", "default.project.json", "wally.toml"]

realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
