[package]
name = "flamenco687/puzzle"
version = "0.2.0"
description = "ECS library for Roblox. Homepage: https://flamenco687.github.io/Puzzle/"

authors = ["flamenco687"]
license = "MIT"

exclude = ["**"]
include = ["lib", "lib/*.lua", "default.project.json", "wally.toml"]

realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
