[package]
name = "flamenco687/puzzle"

description = """
ECS Library for Roblox. \
Heavily inspired by Matter. \
GitHub Repository: https://github.com/flamenco687/Puzzle.
"""

version = "0.1.0"
license = "MIT"
authors = ["flamenco687"]

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.toml"]

realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"

[dependencies]
t = "osyrisrblx/t@3.0.0"
